### ISSUE TITLE
[Issue]: FTBUltimine will not work while using Hephaestus tools

### ISSUE THREAD

**Issue by Almegedus** [The-Nexus-Project/Limitless-Refabricated#5]
### What happened?

Cannot FTBultimine anything with Hephaestus tools

### Pack Version

Version: 1.7.1  Mc:1.1.8.2

### Are you on a Server?

- [ ] Yes.
- [X] No.

### To Reproduce

1. Equip a tool made with Hephaestus. Try to Ultimine.  The tool I am currently using is full iron pickaxe

### Relevant log output / crash report.

```shell
none to add.
```

### Anything else to add?

Great mod pack ! always liked TNP

**Comment by Gbergz** [comment]
Hey, already known and I can't fix it myself unfortunately.
Thanks for the report though! :)
