### ISSUE TITLE
Bewitchment seeds are impossible to get

### ISSUE THREAD

**Issue by Tailsy7767** [The-Nexus-Project/Limitless-Refabricated#6]
What happened?
After playing around both in single player and in a server, ive found that witchery seeds actually dont drop from grass or spawn in any sort of lootable chest. The seed market does not have them either.

Pack Version 1.7.1

Version: 1.18.2
Are you on a Server?

    tried both on and off a server

To Reproduce

Broke a ton of grass, and rei doesnt show any block drop associated with grass regarding the seeds themselves

Relevant log output / crash report.

None

Anything else to add?
None

**Comment by Gbergz** [comment]
Fixed, ish.
Added them to the Market block in 1.8.0.
